### PR TITLE
Allow for text files as assets

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add .txt to the list of asset file extensions.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This should allow us to publish commit IDs eg. https://pr-5845.pfe-preview.zooniverse.org/commit_id.txt

It should also fix the broken text subject in the dev classifier (it's the last frame in the subject viewer.)
https://master.pfe-preview.zooniverse.org/dev/classifier

**Review by camallen — COMMENTED** [review]
I think these changes will work but I'd like to test this in isolation before deploying to all domains. I'll issue another PR for the `sites/star.preview.zooniverse.org.conf` domain first.

**Comment by eatyourgreens** [comment]
Sounds good. Working on this, I discovered that Scribes already has `|txt` in that regex so that could maybe be tested?
https://github.com/zooniverse/static/blob/f4854ec7dcd3863740e5a483a6dab94ce5f924fe/sites/www.scribesofthecairogeniza.org.conf#L11-L12

**Review by camallen — APPROVED** [review]
this should be fine to deploy, and it was tested in #191 

this PR probably needs to be updated based on latest master changes though.

**Pull request merged**
