### PR TITLE
add rewrites for pfe builder docs

### PR DESCRIPTION
**Pull request by marten**
There were only 3 urls that could theoretically be combined into one regex, but i figured it's clearer not to bother in that case.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
It should do. listen.zooniverse.org is hosted on GitHub.

**Comment by marten** [comment]
Yeah sure. Do we want do `help.zooniverse.org` or should we go for something else so that it leaves room to put other static pages into it later on as well? I think everything under `/about` and `/get-involved` could be moved in the same way, though we'll want to set up a theme so that it looks consistent if we do that. I don't feel strongly either way, just asking for opinions here.

**Comment by eatyourgreens** [comment]
I like `help.zooniverse.org`.

**Comment by adammcmaster** [comment]
Yeah help.zooniverse.org sounds good to me.

**Comment by marten** [comment]
Updated. But, https://help.zooniverse.org is giving me a certificate warning. HTTPS seems to work fine on listen.zooniverse.org, did you do anything special or maybe should we just wait for a little bit?

**Comment by adammcmaster** [comment]
Looks like it has a valid certificate now.

**Pull request merged**
